select TITLE, R.BOARD_ID, REPLY_ID, R.WRITER_ID, R.CONTENTS, R.CREATED_DATE
from USED_GOODS_BOARD B
join USED_GOODS_REPLY R
on B.BOARD_ID = R.BOARD_ID
where year(B.CREATED_DATE) = 2022
and month(B.CREATED_DATE) = 10
order by R.CREATED_DATE asc, TITLE asc;